export const RESEARCH_AREAS_FEATURED = [
  'Artificial Intelligence', 'Machine Learning',
  'Data Science', 'Cybersecurity',
  'Software Engineering', 'Computer Networks',
  'Robotics', 'Blockchain Technology',
  'Internet of Things', 'Cloud Computing',
  'Public Health', 'Epidemiology',
  'Biomedical Science', 'Pharmacology',
  'Nursing & Midwifery', 'Mental Health',
  'Community Health', 'Nutrition & Dietetics',
  'Surgery & Medicine', 'Medical Imaging',
  'Climate Science', 'Environmental Science',
  'Renewable Energy', 'Water Resources',
  'Agriculture & Food Security', 'Soil Science',
  'Forestry', 'Marine Science',
  'Wildlife Conservation', 'Urban Planning',
  'Economics & Finance', 'Accounting',
  'Business Management', 'Marketing',
  'Supply Chain', 'Entrepreneurship',
  'International Trade', 'Banking & Finance',
  'Insurance', 'Real Estate',
  'Education & Pedagogy', 'Curriculum Development',
  'Early Childhood Education', 'Special Education',
  'Educational Technology', 'Social Work',
  'Psychology', 'Sociology',
  'Political Science', 'Law & Governance',
]

export const RESEARCH_AREAS = [
  ...RESEARCH_AREAS_FEATURED,
  'Linguistics', 'Philosophy', 'History',
  'Archaeology', 'Anthropology', 'Gender Studies',
  'Cultural Studies', 'Communication Studies',
  'Journalism & Media', 'Library Science',
  'Architecture', 'Civil Engineering',
  'Mechanical Engineering', 'Electrical Engineering',
  'Chemical Engineering', 'Petroleum Engineering',
  'Biomedical Engineering', 'Aerospace Engineering',
  'Industrial Engineering', 'Materials Science',
  'Physics', 'Chemistry', 'Biology',
  'Microbiology', 'Genetics', 'Biochemistry',
  'Zoology', 'Botany', 'Neuroscience',
  'Bioinformatics', 'Mathematics', 'Statistics',
  'Actuarial Science', 'Operations Research',
  'Geographic Information Systems',
  'Remote Sensing', 'Geophysics',
  'Geology', 'Meteorology', 'Oceanography',
]

export const SKILLS_FEATURED = [
  'Data Analysis', 'Research Writing', 'Python',
  'R Programming', 'MATLAB', 'SPSS', 'Statistics',
  'Machine Learning', 'Data Visualization',
  'Literature Review', 'Systematic Review',
  'Field Research', 'Lab Research', 'Survey Design',
  'Qualitative Research', 'Quantitative Research',
  'Mixed Methods', 'Grant Writing',
  'Academic Publishing', 'Project Management',
  'Scientific Writing', 'Presentation Skills',
  'Critical Thinking', 'Problem Solving',
  'Excel & Spreadsheets', 'SQL & Databases',
  'GIS Mapping', 'Bioinformatics',
  'Clinical Research', 'Public Speaking',
  'Web Development', 'Mobile Development',
  'UI/UX Design', 'Graphic Design',
  'Video Production', 'Social Media Research',
  'Content Writing', 'Translation',
  'Community Engagement', 'Policy Analysis',
  'Economic Modelling', 'Financial Analysis',
  'Teaching & Training', 'Mentoring',
  'Team Leadership', 'Event Organisation',
  'Fundraising', 'Networking',
  'Time Management', 'Report Writing',
]

export const SKILLS_OFFERED = [
  ...SKILLS_FEATURED,
  'Stata', 'SAS', 'NVivo', 'Atlas.ti',
  'QGIS', 'ArcGIS', 'AutoCAD', 'Solidworks',
  'Adobe Photoshop', 'Adobe Illustrator',
  'Figma', 'Canva', 'LaTeX', 'Markdown',
  'Git & Version Control', 'Cloud Computing',
  'Blockchain', 'Cybersecurity', 'Network Analysis',
  'Image Processing', 'Natural Language Processing',
  'Computer Vision', 'Signal Processing',
  'Circuit Design', 'PCB Design',
  'Embedded Systems', 'Drone Operation',
  'Lab Safety', 'Microscopy',
  'PCR & Molecular Biology', 'Cell Culture',
  'Animal Handling', 'Plant Identification',
  'Soil Testing', 'Water Quality Testing',
  'Environmental Impact Assessment',
  'Risk Assessment', 'Ethics & Compliance',
  'Intellectual Property', 'Technology Transfer',
]

export const COLLABORATOR_TYPES_FEATURED = [
  'Co-researcher', 'Data Analyst',
  'Research Assistant', 'Mentor', 'Supervisor',
  'Statistician', 'Lab Partner', 'Field Assistant',
  'Technical Writer', 'Grant Writer',
  'Subject Matter Expert', 'Peer Reviewer',
  'Project Manager', 'Programmer / Developer',
  'Designer', 'Survey Administrator',
  'Translator', 'Community Liaison',
  'Policy Advisor', 'Industry Partner',
  'Funding Partner', 'Research Coordinator',
  'Literature Reviewer', 'Editor / Proofreader',
  'Photographer / Videographer',
  'Social Media Manager', 'Ethics Advisor',
  'Legal Advisor', 'Financial Advisor',
  'Equipment Specialist', 'Lab Technician',
  'Clinical Specialist', 'Public Health Officer',
  'Environmental Scientist', 'Agricultural Specialist',
  'Education Specialist', 'Economist', 'Lawyer',
  'Psychologist', 'Sociologist',
  'Journalist / Writer', 'Librarian',
  'Data Engineer', 'Machine Learning Engineer',
  'Cybersecurity Specialist', 'Hardware Engineer',
  'Biomedical Engineer', 'Urban Planner',
  'GIS Specialist', 'Remote Sensing Analyst',
]

export const COLLABORATOR_TYPES = [
  ...COLLABORATOR_TYPES_FEATURED,
  'Accountant', 'Marketing Specialist',
  'Business Analyst', 'Operations Manager',
  'HR Specialist', 'Supply Chain Specialist',
  'Logistics Coordinator', 'IT Support',
  'Database Administrator', 'Network Engineer',
  'Quality Assurance', 'Science Communicator',
  'Museum Curator', 'Archivist', 'Demographer',
  'Geographer', 'Meteorologist', 'Oceanographer',
  'Geologist', 'Physicist', 'Chemist',
  'Botanist', 'Zoologist', 'Microbiologist',
  'Geneticist', 'Neuroscientist',
]
