export const RESEARCH_AREAS = [
  'Agricultural Sciences',
  'Architecture',
  'Arts and Humanities',
  'Biochemistry',
  'Bioinformatics',
  'Biotechnology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Climate Science',
  'Cognitive Science',
  'Communication Studies',
  'Computer Science',
  'Criminology',
  'Cybersecurity',
  'Data Science',
  'Dentistry',
  'Development Studies',
  'Ecology',
  'Economics',
  'Education',
  'Electrical Engineering',
  'Energy Studies',
  'Environmental Science',
  'Epidemiology',
  'Food Science',
  'Forensic Science',
  'Gender Studies',
  'Geography',
  'Geology',
  'Health Informatics',
  'History',
  'Immunology',
  'Industrial Engineering',
  'Information Systems',
  'Information Technology',
  'International Relations',
  'Law',
  'Library Science',
  'Linguistics',
  'Marine Biology',
  'Marketing',
  'Materials Science',
  'Mathematics',
  'Mechanical Engineering',
  'Media Studies',
  'Medicine',
  'Microbiology',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Optometry',
  'Parasitology',
  'Petroleum Engineering',
  'Pharmacology',
  'Philosophy',
  'Physics',
  'Physiology',
  'Plant Science',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Public Health',
  'Radiography',
  'Religious Studies',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Statistics',
  'Surveying',
  'Tourism',
  'Urban Planning',
  'Veterinary Science',
  'Virology',
  'Zoology',
].sort()

export const SKILLS_LIST = [
  'Academic Writing',
  'Arduino Programming',
  'AutoCAD',
  'Biostatistics',
  'Blockchain Development',
  'C++',
  'CRISPR Research',
  'Data Analysis',
  'Data Collection',
  'Data Visualization',
  'Deep Learning',
  'Documentary Research',
  'Drug Formulation',
  'Epidemiological Analysis',
  'Fieldwork',
  'Financial Modeling',
  'Genomics',
  'GIS Mapping',
  'Grant Writing',
  'Graphic Design',
  'HTML/CSS',
  'Image Analysis',
  'Java',
  'JavaScript',
  'Laboratory Management',
  'LaTeX',
  'Literature Review',
  'Machine Learning',
  'MATLAB',
  'Medical Writing',
  'Meta-Analysis',
  'Microscopy',
  'Mixed Methods Research',
  'Molecular Biology',
  'Natural Language Processing',
  'PCR Techniques',
  'Peer Review',
  'Policy Analysis',
  'Presentation Design',
  'Project Management',
  'Proposal Writing',
  'Proteomics',
  'Python',
  'Qualitative Research',
  'Quantitative Research',
  'R Programming',
  'Remote Sensing',
  'Report Writing',
  'Research Ethics',
  'SAS',
  'Scientific Illustration',
  'SPSS',
  'SQL',
  'Statistical Analysis',
  'Structural Analysis',
  'Survey Design',
  'Systematic Review',
  'Technical Drawing',
  'Technical Writing',
  'Tissue Culture',
  'TypeScript',
  'UI/UX Design',
  'Video Production',
  'Web Development',
  'Western Blotting',
].sort()
