'use client'

import { useState, useEffect } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { ArrowLeft, CheckCircle, Clock, Download, Users, FileText, Scale, Calendar } from 'lucide-react'
import { format } from 'date-fns'
import { ListPageSkeleton } from '@/components/ui/skeleton-screens'

export default function AgreementDetailPage() {
  const params = useParams()
  const router = useRouter()
  const agreementId = params.id as string
  const [agreement, setAgreement] = useState<any>(null)
  const [signatories, setSignatories] = useState<any[]>([])
  const [currentUser, setCurrentUser] = useState<any>(null)
  const [mySignatory, setMySignatory] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [signing, setSigning] = useState(false)
  const supabase = createClient()

  useEffect(() => {
    loadData()
  }, [agreementId])

  async function loadData() {
    const { data: { user } } = await supabase.auth.getUser()
    setCurrentUser(user)

    const [agreementRes, sigRes] = await Promise.all([
      supabase.from('coauthorship_agreements')
        .select('*')
        .eq('id', agreementId)
        .single(),
      supabase.from('coauthorship_signatories')
        .select(`
          *,
          profiles(id, full_name, avatar_url, department)
        `)
        .eq('agreement_id', agreementId)
        .order('authorship_position', { ascending: true }),
    ])

    setAgreement(agreementRes.data)
    setSignatories(sigRes.data || [])
    setMySignatory((sigRes.data || []).find((s: any) => s.user_id === user?.id))

    setLoading(false)
  }

  async function handleSign() {
    if (!mySignatory || !currentUser) return
    setSigning(true)

    await supabase
      .from('coauthorship_signatories')
      .update({ has_signed: true, signed_at: new Date().toISOString() })
      .eq('id', mySignatory.id)

    const updatedSigs = signatories.map(s =>
      s.id === mySignatory.id ? { ...s, has_signed: true } : s
    )
    const allSigned = updatedSigs.every(s => s.has_signed)

    if (allSigned) {
      await supabase
        .from('coauthorship_agreements')
        .update({ status: 'active' })
        .eq('id', agreementId)

      await supabase
        .from('notifications')
        .insert({
          user_id: agreement.initiator_id,
          type: 'agreement_signed',
          title: 'Agreement fully signed',
          message: `All parties have signed "${agreement.title}"`,
          link: `/agreements/${agreementId}`,
          is_read: false,
        })
    }

    loadData()
    setSigning(false)
  }

  function generateAgreementText() {
    const s = agreement
    return `CO-AUTHORSHIP AGREEMENT

Title: ${s.title}
Project: ${s.project_title}
Date: ${format(new Date(s.created_at), 'MMMM d, yyyy')}
${s.start_date ? `Start Date: ${s.start_date}` : ''}
${s.end_date ? `End Date: ${s.end_date}` : ''}

RESEARCH OBJECTIVES
${s.research_objectives || 'Not specified'}

METHODOLOGY
${s.methodology || 'Not specified'}

EXPECTED OUTPUTS
${s.expected_outputs || 'Not specified'}

AUTHORSHIP & PUBLICATION
${s.publication_order || 'To be determined by contribution'}

INTELLECTUAL PROPERTY
${s.intellectual_property_terms}

DISPUTE RESOLUTION
${s.dispute_resolution}

${s.additional_terms ? `ADDITIONAL TERMS\n${s.additional_terms}\n` : ''}
SIGNATORIES
${signatories.map((sig, i) =>
  `${i + 1}. ${sig.profiles?.full_name} - ${sig.role}${sig.has_signed ? ' ✓ SIGNED' : ' (Pending)'}`
).join('\n')}

Generated by ResearchFlow · researchflowafrica.com`
  }

  function downloadAgreement() {
    const text = generateAgreementText()
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${agreement.title.replace(/\s+/g, '_')}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (loading) return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
      <ListPageSkeleton type="card" count={3} />
    </div>
  )

  if (!agreement) return null

  const signedCount = signatories.filter(s => s.has_signed).length
  const canSign = mySignatory && !mySignatory.has_signed

  const statusColors: Record<string, string> = {
    draft: 'bg-gray-500/10 text-gray-400 border-gray-500/20',
    pending: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    active: 'bg-green-500/10 text-green-400 border-green-500/20',
    completed: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6 pb-10">

      <Button variant="ghost" size="sm" onClick={() => router.back()} className="gap-2">
        <ArrowLeft className="w-4 h-4" />
        Back
      </Button>

      {/* Header */}
      <div className="bg-card border border-border rounded-2xl p-6 space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-2 flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <Badge variant="outline" className={`text-xs ${statusColors[agreement.status]}`}>
                {agreement.status.toUpperCase()}
              </Badge>
              <span className="text-xs text-muted-foreground">
                {signedCount}/{signatories.length} signed
              </span>
            </div>
            <h1 className="text-xl font-bold">{agreement.title}</h1>
            <p className="text-muted-foreground">{agreement.project_title}</p>
          </div>
          <Button variant="outline" size="sm" onClick={downloadAgreement} className="gap-2 shrink-0">
            <Download className="w-4 h-4" />
            Download
          </Button>
        </div>

        {(agreement.start_date || agreement.end_date) && (
          <div className="flex gap-4 text-sm text-muted-foreground">
            {agreement.start_date && (
              <span className="flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                Start: {agreement.start_date}
              </span>
            )}
            {agreement.end_date && (
              <span className="flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                End: {agreement.end_date}
              </span>
            )}
          </div>
        )}

        {canSign && (
          <div className="pt-2 border-t border-border">
            <div className="bg-primary/5 border border-primary/20 rounded-xl p-4 space-y-3">
              <p className="text-sm font-medium">Your signature is required</p>
              <p className="text-sm text-muted-foreground">
                By signing you agree to all terms outlined in this co-authorship agreement.
              </p>
              <Button onClick={handleSign} disabled={signing} className="gap-2">
                {signing ? (
                  <div className="w-4 h-4 rounded-full animate-spin border-2 border-white border-t-transparent" />
                ) : (
                  <CheckCircle className="w-4 h-4" />
                )}
                Sign Agreement
              </Button>
            </div>
          </div>
        )}
      </div>

      {/* Signatories */}
      <div className="bg-card border border-border rounded-2xl p-6 space-y-4">
        <h2 className="font-semibold flex items-center gap-2">
          <Users className="w-4 h-4" />
          Signatories
        </h2>
        <div className="space-y-3">
          {signatories.map((sig, i) => (
            <div key={sig.id} className="flex items-center gap-3">
              <span className="text-sm font-bold text-muted-foreground w-5 text-center shrink-0">{i + 1}</span>
              <Avatar className="w-9 h-9">
                <AvatarImage src={sig.profiles?.avatar_url} />
                <AvatarFallback>{sig.profiles?.full_name?.charAt(0)}</AvatarFallback>
              </Avatar>
              <div className="flex-1 min-w-0">
                <p className="font-medium text-sm">{sig.profiles?.full_name}</p>
                <p className="text-xs text-muted-foreground">
                  {sig.role}{sig.contribution && ` · ${sig.contribution}`}
                </p>
              </div>
              <div className="shrink-0">
                {sig.has_signed ? (
                  <div className="flex items-center gap-1 text-green-400 text-xs">
                    <CheckCircle className="w-4 h-4" />
                    Signed
                  </div>
                ) : (
                  <div className="flex items-center gap-1 text-muted-foreground text-xs">
                    <Clock className="w-4 h-4" />
                    Pending
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Agreement Sections */}
      {[
        { title: 'Research Objectives', icon: FileText, content: agreement.research_objectives },
        { title: 'Methodology', icon: FileText, content: agreement.methodology },
        { title: 'Expected Outputs', icon: FileText, content: agreement.expected_outputs },
        { title: 'Authorship & Publication', icon: Scale, content: agreement.publication_order },
        { title: 'Intellectual Property', icon: Scale, content: agreement.intellectual_property_terms },
        { title: 'Dispute Resolution', icon: Scale, content: agreement.dispute_resolution },
        { title: 'Additional Terms', icon: FileText, content: agreement.additional_terms },
      ]
        .filter(s => s.content)
        .map(section => (
          <div key={section.title} className="bg-card border border-border rounded-2xl p-6 space-y-3">
            <h2 className="font-semibold flex items-center gap-2">
              <section.icon className="w-4 h-4 text-primary" />
              {section.title}
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
              {section.content}
            </p>
          </div>
        ))
      }

      <p className="text-xs text-muted-foreground text-center">
        Created {format(new Date(agreement.created_at), 'MMMM d, yyyy')} · Generated by ResearchFlow
      </p>
    </div>
  )
}
